### ISSUE TITLE
Crash of game with version biomesinjars_fabric_1.1.2

### ISSUE THREAD

**Issue by Flamaghl** [Keksuccino/Biomes-in-Jars#8]
Hello,

Since I updated biomesinjars_fabric_1.1.2, the game has been crashing every time I try to open it (not at world opening, but at game opening)
When I use biomesinjars_fabric_1.1.1 version of the mod, it is working fine both at game opening and world opening levels

I am on Fabric 0.14.15, and MC 1.19.2

It creates no crash report, but exit code is 1 :( 

The only strange part in Log is : 
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at java.base/java.util.Objects.checkIndex(Objects.java:359)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at java.base/java.util.ArrayList$SubList.get(ArrayList.java:1149)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:306)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:282)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.createFunction(MathBuilder.java:439)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:266)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:308)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:283)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.geckolib3.core.molang.MolangParser.parseSymbolsMolang(MolangParser.java:228)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.geckolib3.core.molang.MolangParser.parseOneLine(MolangParser.java:216)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.geckolib3.core.molang.MolangParser.parseExpression(MolangParser.java:174)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.geckolib3.core.molang.MolangParser.parseJson(MolangParser.java:154)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.geckolib3.util.json.JsonKeyFrameUtils.parseExpression(JsonKeyFrameUtils.java:179)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.geckolib3.util.json.JsonKeyFrameUtils.convertJson(JsonKeyFrameUtils.java:57)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.geckolib3.util.json.JsonKeyFrameUtils.convertJsonToRotationKeyFrames(JsonKeyFrameUtils.java:173)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.geckolib3.util.json.JsonAnimationUtils.deserializeJsonToAnimation(JsonAnimationUtils.java:278)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.geckolib3.file.AnimationFileLoader.loadAllAnimations(AnimationFileLoader.java:32)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.geckolib3.resource.GeckoLibCache.lambda$reload$0(GeckoLibCache.java:73)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.geckolib3.resource.GeckoLibCache.lambda$loadResources$5(GeckoLibCache.java:91)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at java.base/java.util.Objects.checkIndex(Objects.java:359)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at java.base/java.util.ArrayList$SubList.get(ArrayList.java:1149)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:306)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:282)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.createFunction(MathBuilder.java:439)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:266)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:308)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:283)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.geckolib3.core.molang.MolangParser.parseSymbolsMolang(MolangParser.java:228)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.geckolib3.core.molang.MolangParser.parseOneLine(MolangParser.java:216)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.geckolib3.core.molang.MolangParser.parseExpression(MolangParser.java:174)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.geckolib3.core.molang.MolangParser.parseJson(MolangParser.java:154)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.geckolib3.util.json.JsonKeyFrameUtils.parseExpression(JsonKeyFrameUtils.java:179)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.geckolib3.util.json.JsonKeyFrameUtils.convertJson(JsonKeyFrameUtils.java:57)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.geckolib3.util.json.JsonKeyFrameUtils.convertJsonToRotationKeyFrames(JsonKeyFrameUtils.java:173)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.geckolib3.util.json.JsonAnimationUtils.deserializeJsonToAnimation(JsonAnimationUtils.java:278)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.geckolib3.file.AnimationFileLoader.loadAllAnimations(AnimationFileLoader.java:32)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.geckolib3.resource.GeckoLibCache.lambda$reload$0(GeckoLibCache.java:73)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at software.bernie.geckolib3.resource.GeckoLibCache.lambda$loadResources$5(GeckoLibCache.java:91)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[14:38:45] [Worker-Main-7/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

I am using latest versions of Konkrete, Fabric and GeckoLib
Regards,

**Comment by Keksuccino** [comment]
Fixed in Biomes In Jars v1.1.3!
